USB_VID = 0x239A
USB_PID = 0x80B4
USB_PRODUCT = "nice!nano"
USB_MANUFACTURER = "Nice Keyboards"

MCU_CHIP = nrf52840

INTERNAL_FLASH_FILESYSTEM = 1

# CIRCUITPY_OPTIMIZE_PROPERTY_FLASH_SIZE = 1

CIRCUITPY_ENABLE_MPY_NATIVE = 1

CIRCUITPY_AESIO = 0
CIRCUITPY_BITBANGIO = 0
CIRCUITPY_MSGPACK = 0
CIRCUITPY_TOUCHIO = 0

CIRCUITPY_HID = 1
CIRCUITPY_SYNTHIO = 0
CIRCUITPY_ULAB = 0

FROZEN_MPY_DIRS += $(TOP)/frozen/Adafruit_CircuitPython_BLE
FROZEN_MPY_DIRS += $(TOP)/frozen/Adafruit_CircuitPython_Display_Text
# FROZEN_MPY_DIRS += $(TOP)/frozen/kmk_firmware
